import { Theme, ThemeName } from '@/types';

export const themes: Record<ThemeName, Theme> = {
  pastel: {
    name: 'pastel',
    label: 'Pastel Pop',
    emoji: '🌸',
    bg: 'bg-pink-50',
    bgGradient: 'from-pink-50 via-purple-50 to-blue-50',
    card: 'bg-white/80',
    cardBorder: 'border-pink-100',
    accent: 'from-pink-400 to-purple-400',
    accentText: 'text-pink-500',
    accentBg: 'bg-pink-100',
    text: 'text-gray-800',
    subtext: 'text-gray-500',
    highlight: 'text-purple-500',
    pattern: 'bg-[radial-gradient(#f9a8d4_1px,transparent_1px)] [background-size:24px_24px]',
    nav: 'bg-white/70 border-pink-100',
  },
  sunshine: {
    name: 'sunshine',
    label: 'Sunshine',
    emoji: '☀️',
    bg: 'bg-yellow-50',
    bgGradient: 'from-yellow-50 via-orange-50 to-amber-50',
    card: 'bg-white/80',
    cardBorder: 'border-yellow-200',
    accent: 'from-yellow-400 to-orange-400',
    accentText: 'text-yellow-600',
    accentBg: 'bg-yellow-100',
    text: 'text-gray-800',
    subtext: 'text-gray-500',
    highlight: 'text-orange-500',
    pattern: 'bg-[radial-gradient(#fde68a_1px,transparent_1px)] [background-size:24px_24px]',
    nav: 'bg-white/70 border-yellow-100',
  },
  ocean: {
    name: 'ocean',
    label: 'Ocean',
    emoji: '🌊',
    bg: 'bg-cyan-50',
    bgGradient: 'from-cyan-50 via-teal-50 to-blue-50',
    card: 'bg-white/80',
    cardBorder: 'border-cyan-200',
    accent: 'from-cyan-400 to-blue-400',
    accentText: 'text-cyan-600',
    accentBg: 'bg-cyan-100',
    text: 'text-gray-800',
    subtext: 'text-gray-500',
    highlight: 'text-blue-500',
    pattern: 'bg-[radial-gradient(#a5f3fc_1px,transparent_1px)] [background-size:24px_24px]',
    nav: 'bg-white/70 border-cyan-100',
  },
  candy: {
    name: 'candy',
    label: 'Candy',
    emoji: '🍬',
    bg: 'bg-rose-50',
    bgGradient: 'from-rose-50 via-fuchsia-50 to-pink-50',
    card: 'bg-white/80',
    cardBorder: 'border-rose-200',
    accent: 'from-rose-400 to-fuchsia-400',
    accentText: 'text-rose-500',
    accentBg: 'bg-rose-100',
    text: 'text-gray-800',
    subtext: 'text-gray-500',
    highlight: 'text-fuchsia-500',
    pattern: 'bg-[radial-gradient(#fda4af_1px,transparent_1px)] [background-size:24px_24px]',
    nav: 'bg-white/70 border-rose-100',
  },
  neon: {
    name: 'neon',
    label: 'Neon',
    emoji: '⚡',
    bg: 'bg-gray-950',
    bgGradient: 'from-gray-950 via-purple-950 to-gray-950',
    card: 'bg-gray-900/80',
    cardBorder: 'border-purple-500/30',
    accent: 'from-green-400 to-cyan-400',
    accentText: 'text-green-400',
    accentBg: 'bg-green-900/30',
    text: 'text-gray-100',
    subtext: 'text-gray-400',
    highlight: 'text-cyan-400',
    pattern: 'bg-[radial-gradient(#4ade80_1px,transparent_1px)] [background-size:24px_24px] opacity-10',
    nav: 'bg-gray-900/80 border-purple-500/20',
  },
  galaxy: {
    name: 'galaxy',
    label: 'Galaxy',
    emoji: '🌌',
    bg: 'bg-indigo-950',
    bgGradient: 'from-indigo-950 via-purple-950 to-violet-950',
    card: 'bg-indigo-900/50',
    cardBorder: 'border-indigo-500/30',
    accent: 'from-violet-400 to-pink-400',
    accentText: 'text-violet-300',
    accentBg: 'bg-violet-900/30',
    text: 'text-indigo-50',
    subtext: 'text-indigo-300',
    highlight: 'text-pink-400',
    pattern: 'bg-[radial-gradient(#818cf8_1px,transparent_1px)] [background-size:32px_32px] opacity-20',
    nav: 'bg-indigo-900/60 border-indigo-500/20',
  },
};

export const defaultTheme: ThemeName = 'pastel';
